sudo: required
services: 
  - docker

script:
  - docker build -t lhemenez/web ./web
  - docker build -t lhemenez/nginx ./nginx
  # Logging in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Taking images and pushing them to DockerHub
  - docker push lhemenez/web
  - docker push lhemenez/nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: ChowSafely_v2
  env: ChowsafelyV2-env
  bucket_name: elasticbeanstalk-us-east-2-077457045789
  bucket_path: ChowSafely_v2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
