version: '3'
services:
  web:
    restart: always
    build:
      context: ./web
    env_file: .env
    environment:
      - CLIENT_ID
      - API_KEY
      - USERNAME
    expose:
      - "8000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
    links:
      - web
    expose:
      - "80"